import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Top from '../components/Top'
import { client } from '../libs/client'
import { Blog } from '../types/blog'

type Props = {
	blogs: Blog[]
}

export default function Home({ blogs }: Props) {
	return (
		<>
			<Head>
				<title>Next.js Blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="pt-4">
				<p className="text-gray-300 tracking-[5px] text-center hover:text-white">
					Frontend Developer / React.js / Next.js / TypeScript
				</p>
			</div>

			<div className="text-center mt-4  text-white transition hover:scale-105 hover:ease-in hover:duration-105">
				React.js
			</div>

			<div>
				<Top blogs={blogs} />
			</div>
		</>
	)
}

export const getServerSideProps: GetServerSideProps = async () => {
	const data = await client.get({ endpoint: 'blogs' })

	return {
		props: {
			blogs: data.contents,
		},
	}
}
